---
framework: jest
preRun:
     command:
        - yarn install
        - yarn run build
preMerge:
  pattern:
    - "./test/**/*{.ts,.tsx}"
postMerge:
  pattern: 
    - "./test/**/*{.ts,.tsx}"
postRun:
     command:
        - yarn --version
version: 1.0.0
